# Generated by Django 6.0.2 on 2026-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('courses', models.TextField()),
                ('fee_structure', models.TextField()),
                ('activities', models.TextField()),
                ('placements', models.TextField()),
                ('gate_results', models.TextField()),
            ],
        ),
    ]
