# Generated by Django 6.0.2 on 2026-02-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='category',
            new_name='fees',
        ),
        migrations.RemoveField(
            model_name='college',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='college',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='college',
            name='gate_results',
        ),
        migrations.AddField(
            model_name='college',
            name='gate_students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
