# Generated by Django 6.0.2 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='average_package',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='clubs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='culturals',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='highest_package',
            field=models.CharField(default='Not Updated', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_images/'),
        ),
        migrations.AddField(
            model_name='college',
            name='labs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='top_companies',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='college',
            name='courses',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='college',
            name='fees',
            field=models.CharField(default='Not Updated', max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='gate_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='placements',
            field=models.TextField(default=''),
        ),
    ]
